### PR TITLE
Bug fix: can't send result with raw score 0

### PR DESCRIPTION
**Pull request by sergey-rud**

### CODE REVIEW

**Comment by garemoko** [comment]
Hi! Thanks for the contribution. This particular bug is already covered by https://github.com/RusticiSoftware/TinCanPHP/pull/49

**Comment by sergey-rud** [comment]
Hi, well, it would be nice to merge any of those pull requests as soon as possible. Considering that I am not the first person with the same problem :)

**Comment by brianjmiller** [comment]
I am working through open pull requests today and going roughly in order that they were opened, this is going to cause some conflicts as I go which I will attempt to resolve myself. Conflicts that can't be resolved in a fairly straight forward manner may have to go back to the author for correction. My intention is to work through the back log with non-PHP7 related PRs getting in first for a last minor version bump to the library, followed by the PHP7 change in a major version bump. It may not be possible to get all open PRs merged today.

**Comment by brianjmiller** [comment]
Should be handled by #59, please test and open an issue if still a problem. #59 will land in the next release.

**Pull request closed without merging**
