### PR TITLE
PHP 8 compatibility #108

### PR DESCRIPTION
**Pull request by Natshah**

### CODE REVIEW

**Review by vgulshan1985 — APPROVED** [review]

**Comment by TheGarious** [comment]
@brianjmiller @reedmclean Can you accept this pull request ?

**Comment by jaswinsingh** [comment]
@brianjmiller @reedmclean Can you please merge this?

**Comment by bob-hinrichs** [comment]
Can we get a new tag please with this merged (along with any other php 8 changes needed)?  Many are waiting!

**Comment by philoSurfer** [comment]
Bump... this is causing all kinds of downstream issues.

**Comment by apurav2702** [comment]
is there any way to use the latest changes in PHP version dependency without releasing a new tag maybe by using a patch

**Comment by bob-hinrichs** [comment]
Yes, I think we can do this: "rusticisoftware/tincan": "dev-master#19acfc8"

**Pull request merged**
