### PR TITLE
Fixes `Class 'TinCan\ErrorException' not found`

### PR DESCRIPTION
**Pull request by garemoko**
Fixes `Class 'TinCan\ErrorException' not found`

### CODE REVIEW

**Comment by garemoko** [comment]
@brianjmiller really minor bugfix, ready for review

**Comment by WillSkates** [comment]
@garemoko this is already fixed in #60 isnt it?

**Comment by garemoko** [comment]
@WillSkates ha! Yes it is, via a different method. I'm ok with either method.

Looks like you used the same approach here: https://github.com/RusticiSoftware/TinCanPHP/pull/47/files#diff-603c9e0a45dc5c5ce0cff69bc586edb1L130

**Comment by WillSkates** [comment]
@garemoko Yep :D. Theres more in there as well [i.e.](https://github.com/RusticiSoftware/TinCanPHP/pull/47/files#diff-b5558596d61c6c61a22b0c8329b597bfR60).

**Comment by WillSkates** [comment]
https://github.com/RusticiSoftware/TinCanPHP/blob/master/tests/RemoteLRSTest.php#L340 seems to be the issue with 5.6. It seems like Scorm cloud might have some kind of rate limiting going on.

**Comment by WillSkates** [comment]
Shame we can't check the response code.

**Comment by garemoko** [comment]
Yeh, as discussed on gitter, I'm confident this should pass normally. We saw this glitch on the first commit on the previous PR too: https://github.com/RusticiSoftware/TinCanPHP/pull/65

**Comment by WillSkates** [comment]
@garemoko 'success' isn't a great word to indicate why something has failed. Lets fix that as well.
Agreed this should pass normally.

**Comment by brianjmiller** [comment]
Determined that this patch wasn't sufficient cause we have another instance of `ErrorException` in the `catch`, which I'll patch momentarily. I suppose that makes the import approach slightly better, but will still use this approach.

**Comment by brianjmiller** [comment]
Patched in https://github.com/RusticiSoftware/TinCanPHP/commit/95f49d6e9f56badd4bd9aad7141578e0840ee471

**Comment by brianjmiller** [comment]
Released in 0.40.1.

**Pull request merged**
