### PR TITLE
Enable setting headers on `RemoteLRS.queryStatements`

### LINKED ISSUE #26: Allow headers to be set when querying statements
It would be helpful to be able to pass options to ```sendRequest``` via ```queryStatements```, for example headers such as ```Accept-language```. 

The code might look something like (although $options should really be optional): 

```
    public function queryStatementsWithOptions($query, $options) {
        $requestCfg = array(
            'params' => $this->_queryStatementsRequestParams($query),
        );

        $response = $this->sendRequest('GET', 'statements', $requestCfg, $options);

        if ($response->success) {
            $this->_queryStatementsResult($response);
        }

        return $response;
    }
```

### PR DESCRIPTION
**Pull request by brianjmiller**
Fixes #26.

### CODE REVIEW

**Comment by brianjmiller** [comment]
@garemoko care to review?

**Comment by garemoko** [comment]
Code looks good. Would be nice to include a test.

**Comment by garemoko** [comment]
The test would go around here: https://github.com/RusticiSoftware/TinCanPHP/pull/67

I'm thinking we set the X-Experience-API-Version to "11" and test for a 400 response.

**Comment by brianjmiller** [comment]
Tests would be good, but at this point I'm trying to get all of the things in, honestly I think to get better coverage in this lib we need to switch to mocking the LRS or the HTTP request, and that is a much bigger task than I'm willing (or able) to take on at the moment.

**Comment by garemoko** [comment]
Cool. If I get some time this week I might add the test I suggested as a separate PR.

**Pull request merged**
