### PR TITLE
Add `proxy` option to RemoteLRS

### LINKED ISSUE #63: Adding proxy parameters if necessary
If your Moodle server  is behind a proxy server, you have to add a parameter ad-hoc like this:

        _$http = array(
            //
            // redirects are not part of the spec so LRSs shouldn't be returning them
            //
            'max_redirects' => 0,
            //
            // this is here for some proxy handling
            //
            'request_fulluri' => 1,
            **'proxy'   => '192.168.100.XXX:8080',**
            //
            // switching this to false causes non-2xx/3xx status codes to throw exceptions
            // but we need to handle the "error" status codes ourselves in some cases
            //
            'ignore_errors' => true,
            'method' => $method,
            'header' => array(
                'X-Experience-API-Version: ' . $this->version
            ),
        );_

### PR DESCRIPTION
**Pull request by brianjmiller**
Fixes #63.

### CODE REVIEW

**Comment by brianjmiller** [comment]
@deedey

**Comment by nadavkav** [comment]
I can. just one questions...
I assume $proxy take the full: "protocol://server-ip:port" syntax?

**Comment by nadavkav** [comment]
Works great :smile:

**Comment by nadavkav** [comment]
Added following code, to test it under Moodle which is using the [xapi-logstore plugin](https://moodle.org/plugins/logstore_xapi)
https://github.com/LearningLocker/xAPI-Recipe-Emitter/blob/master/src/Repository.php#L15
```
  global $CFG;
  $this->store = $store;
  $this->store->setProxy($CFG->proxyhost.':'.$CFG->proxyport);
```

**Comment by deedey** [comment]
@brianjmiller @nadavkav, 
I'll test it tomorrow but I think it works after reading changes. 
Thank's @brianjmiller

**Comment by brianjmiller** [comment]
@nadavkav yeah, I suspect this is a rare enough need that I just left it wide open to support whatever the underlying PHP option is and that people who get to this point of realizing what they need will know either how to create the value or will make their way here or to the issue.

**Comment by nadavkav** [comment]
Great! Thanks for the quick fix :smile: 
btw, it would be nice to also include in this patch a $proxyuser & $proxypass, which are different (of course) from the LRS $user & $pass set by the setAuth() function.
You will need to add the following header:
```
'http' => array( 
                 'proxy' => 'tcp://proxyip:8080', 
                 'header' => array( "Proxy-Authorization: Basic $auth" )
) 
```
Where $auth is a Base64 encrypted "username: password".

**Comment by brianjmiller** [comment]
That would probably come in as a more generic array of headers for all requests at the `RemoteLRS` level rather than specific to the proxy functionality.

**Comment by nadavkav** [comment]
Indeed. but can you just push the "Proxy-Authorization: Basic $auth" into that array, if it already exists? (maybe)

**Comment by brianjmiller** [comment]
@nadavkav see latest commit, does that work?

**Comment by brianjmiller** [comment]
The generic headers thing definitely puts onus on the user to not do stupid things, like set a single string in there, or pass in malformed arrays/header values, etc. but like the proxy setting I think this is far enough in the weeds that if someone is using it they better understand what they are doing and likely have even read the source.

**Comment by nadavkav** [comment]
Thank for improving the code. Indeed, it looks much more useful, and generic.

I was actually thinking on a less generic implementation, maybe like:
`setProxy($proxy, $user=null, $pass=null)`
And then, setting the $header with a direct:
```
if (isset($user)) {
$auth = MD5("$user:$pass");
$header[] = "Proxy-Authorization: Basic $auth";
}
```
So the external developer (that is using this library) does not need to know the exact syntax and spec of the proxy authentication headers.
What do you think?

**Comment by brianjmiller** [comment]
While reasonable I think it is a low enough use case that I'd rather not include it here as ultimately it is effectively untestable by us, but if they know they are in charge of their proxy string handling, etc. they'll presumably have a way to test it, etc.

**Comment by nadavkav** [comment]
Good enough for me. but I will wait a while and let the folks at LL see if they have any comments too.
Thank you very much on being very quick on solving this!

**Comment by brianjmiller** [comment]
👍  heh, on that last part you just got lucky :-).

**Pull request merged**
