### PR TITLE
getTimestamp() UTC issue #64

### PR DESCRIPTION
**Pull request by lewyckoff**
Per this issue:
https://github.com/RusticiSoftware/TinCanPHP/issues/64

### CODE REVIEW

**Comment by garemoko** [comment]
Thanks for this @lewyckoff!

@brianjmiller (or any other regex ninja) any suggestion on how to amend the test regex so that it checks that the timestamp is always UTC 0? 

See: 
https://github.com/RusticiSoftware/TinCanPHP/blob/master/tests/UtilTest.php#L37

**Comment by garemoko** [comment]
Actually, I think I figured it out using http://regexr.com/

```
$this->assertRegExp('/\d\d\d\d-[01]\d-[0123]\dT[012]\d:[012345]\d:[012345]\d\.\d\d\d\+00:00/', $result);
```

@lewyckoff do you want to incorporate that in your PR and see if it still passes?

**Comment by garemoko** [comment]
@lewyckoff perfect. Thanks!

+1

**Comment by WillSkates** [comment]
@lewyckoff @garemoko Looks good! +1 from me as well if it counts.

Only thing I'd consider is using DateTimeImmutable instead of DateTime but I'm guessing that would wreak havock with type hinting & checking elsewhere.

**Pull request merged**
